import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Seller - Stores",
  description: "Generated by create next app",
};

const layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return children;;
}

export default layout;
