import type { Metadata } from "next";
import SellerAuthWrapper from "@/components/seller/widgets/SellerAuthWrapper";

export const metadata: Metadata = {
  title: "Seller Portal- Register",
  description: "Generated by create next app",
};

const layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <SellerAuthWrapper>
      {children}
    </SellerAuthWrapper>
  );
}

export default layout;
