import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Seller Portal",
  description: "Generated by create next app",
};

export default function SellerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col flex-1">
      {children}
    </div>
  );
}