import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Seller Portal - Register",
  description: "Generated by create next app",
};

const SellerRegisterLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return children;;
}

export default SellerRegisterLayout;